# This is a basic workflow to help you get started with Actions

name: Demo1_CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker tag 5ce65d7b0fde lalitku/ucv-ext-azure:${{ github.run_number }}
        docker images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: lalitku
        password: Lalit/2698
    - name: Push
      run: |
          docker push lalitku/ucv-ext-azure:${{ github.run_number }}
