name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker tag 5ce65d7b0fde lalitku/ucv-ext-azure:${{ github.run_number }}
        docker images
        docker login -u lalitku -p Lalit/2698 https://docker.io
        docker push lalitku/ucv-ext-azure:${{ github.run_number }}
        
