name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker pull lalitku/ucv-ext-azure:4.0.2
        docker tag lalitku/ucv-ext-azure:4.0.2 lalitku/ucv-ext-azure:${{ github.run_number }}
        docker ps
        docker login -u lalitku -p Lalit/2698 https://docker.io
        docker push lalitku/ucv-ext-azure:${{ github.run_number }}
        
