name: Hybrid App Build Process

# Controls when the workflow will run
runs-on: self-hosted
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker pull minddocdev/node-alpine:latest
        docker tag minddocdev/node-alpine:latest lalitku/hybrid-comp-image:${{ github.run_number }}
        docker images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: lalitku
        password: Lalit/2698
    - name: Push
      run: |
          docker push lalitku/hybrid-comp-image:${{ github.run_number }}
    - name: Import Component Into UCD
      run: |
        curl --insecure --request PUT 'https://10.134.119.198:8443/cli/component/integrate' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"component": "HybridAppComp1","properties": {"version": ${{ github.run_number }},"description": ""}}'
          
