name: Simple Build Job
on:
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]
  # push:
  #   branches: [ "main" ]
  

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Token
        id: curl
        run: |
         echo hello
