name: Simple Build Job
on:
  workflow_dispatch:
  

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Token
        id: curl
        run: |
         echo hello
